### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by loe** [phrawzty/rabbitmq-collectd-plugin#2]
collectd 4.10.1

I have a memory leak with this script, it eventually uses up all the memory on the machine and oomkiller axes collectd. I have other python scripts that run with no problems though.

Does this work for you? 32/64bit?

**Comment by loe** [comment]
I'm bumping to 4.10.4 to see if it was an issue with that.

**Comment by phrawzty** [comment]
I've only run it in a 64 bit envinronment, and I've not experienced any memory leaks so far.  Keep me posted on how 4.10.4 goes for you.

**Comment by loe** [comment]
What version are you running with?

**Comment by phrawzty** [comment]
That's an excellent question; as I am on an extended vacation right now, I really couldn't tell you. :-)

**Comment by loe** [comment]
I've upgraded to 4.10.4, and it is not resolved. I run different python plugins on other instances and have no problems. Somewhere in my modifications to the script I created a memory leak.

**Comment by phrawzty** [comment]
Thanks for letting me know - I'll roll it back.  Unfortunately I'm not in a position to test it right now, so...
